FROM openjdk:8
EXPOSE 8080
ADD target /home/kiranpg94gmail/eclipse-workspace/SamplecodeProject/src/samplecodeprojectclass.jar samplecodeprojectclass.jar
ENTRYPOINT ["java","-jar","/samplecodeprojectclass.jar"]